version: '3.8'

services:
  # Qdrant vector data base
  qdrant:
    image: qdrant/qdrant:latest
    container_name: rtc-qdrant
    ports:
      - "6333:6333"
      - "6334:6334"
    volumes:
      - ./qdrant_data:/qdrant/storage # persistence mounting

  # Neo4j graph data base
  neo4j:
    image: neo4j:latest
    container_name: rtc-neo4j
    ports:
      - "7474:7474"
      - "7687:7687"
    environment:
      - NEO4J_AUTH=neo4j/testpassword123
    volumes:
      - ./neo4j_data:/data # persistence mounting
  